---
title: Catch 块永远不会到达;<exception>已在上面处理同一个 Try 语句
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 3bbb76264ba28f7f74e1ec626adf2c09a50273d4
ms.sourcegitcommit: bef803e2025642df39f2f1e046767d89031e0304
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 02/15/2019
ms.locfileid: "56304318"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Catch 块永远不会到达;\<异常 > 已在上面处理同一个 Try 语句
无法达到代码中的 `Catch` 块，因为它已经在前面的 `Try` 块中得到处理。  
  
默认情况下，此消息是一个警告。 若要深入了解如何隐藏警告或将警告视为错误，请参阅 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)。
  
 **错误 ID:** BC42031  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
-   删除多余的语句。  
  
## <a name="see-also"></a>请参阅

- [如何使用 try/catch 块来捕获异常](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [使用用户筛选的异常处理程序](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
